// Golden reference validation: GPU inference shaders vs PyTorch model output.
//
// SYNC REQUIREMENT: The golden reference file (tests/data/golden_ref.bin) is
// generated by tests/generate_golden_reference.py, which imports the DeniUNet
// model directly from training/deni_train/models/. If the training model
// architecture changes (e.g. adding temporal anti-aliasing, changing channel
// counts, modifying layer structure), the golden reference must be regenerated:
//
//   cd training
//   python ../tests/generate_golden_reference.py --output ../tests/data/golden_ref.bin
//
// This will cause the GPU tests to fail if the GLSL compute shaders have not
// been updated to match the new architecture. This is intentional: the golden
// reference serves as a contract between the training model and the GPU shaders.

#include <catch2/catch_test_macros.hpp>
#include <catch2/catch_approx.hpp>

#include <volk.h>

#include "../app/core/vulkan_context.h"
#include "shared_context.h"
#include "../denoise/src/vulkan/MlInference.h"
#include "../denoise/src/vulkan/WeightLoader.h"

#include <deni/vulkan/Denoiser.h>

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <fstream>
#include <memory>
#include <optional>
#include <string>
#include <vector>

#ifndef DENI_SHADER_SPV_DIR
#define DENI_SHADER_SPV_DIR "build/deni_shaders"
#endif

#ifndef DENI_TEST_DATA_DIR
#define DENI_TEST_DATA_DIR "tests/data"
#endif

namespace {

// ---------------------------------------------------------------------------
// FP16 conversion utilities
// ---------------------------------------------------------------------------

float HalfToFloat(uint16_t half) {
    uint32_t sign = static_cast<uint32_t>(half & 0x8000) << 16;
    uint32_t exponent = (half >> 10) & 0x1F;
    uint32_t mantissa = half & 0x3FF;

    if (exponent == 0) {
        if (mantissa == 0) {
            float f;
            std::memcpy(&f, &sign, sizeof(float));
            return f;
        }
        while (!(mantissa & 0x400)) {
            mantissa <<= 1;
            exponent--;
        }
        exponent++;
        mantissa &= ~0x400u;
    } else if (exponent == 31) {
        uint32_t result = sign | 0x7F800000 | (mantissa << 13);
        float f;
        std::memcpy(&f, &result, sizeof(float));
        return f;
    }

    uint32_t result = sign | ((exponent + 127 - 15) << 23) | (mantissa << 13);
    float f;
    std::memcpy(&f, &result, sizeof(float));
    return f;
}

// ---------------------------------------------------------------------------
// Golden reference binary format (produced by generate_golden_reference.py)
// ---------------------------------------------------------------------------

struct GoldenReference {
    uint32_t width = 0;
    uint32_t height = 0;
    uint32_t base_channels = 0;
    std::vector<uint8_t> denimodel_bytes;

    std::vector<uint16_t> diffuse;          // [H][W][4] RGBA16F
    std::vector<uint16_t> specular;         // [H][W][4] RGBA16F
    std::vector<uint16_t> normals;          // [H][W][4] RGBA16F
    std::vector<uint16_t> depth;            // [H][W][1] R16F
    std::vector<uint16_t> motion;           // [H][W][2] RG16F
    std::vector<uint16_t> diffuse_albedo;   // [H][W][4] RGBA16F
    std::vector<uint16_t> specular_albedo;  // [H][W][4] RGBA16F

    std::vector<float> expected_output;  // [3][H][W] channel-major FP32 (remodulated)
};

std::optional<GoldenReference> LoadGoldenReference(const std::string& path) {
    std::ifstream file(path, std::ios::binary);
    if (!file.is_open()) return std::nullopt;

    auto read_u32 = [&](uint32_t& val) -> bool {
        return static_cast<bool>(file.read(reinterpret_cast<char*>(&val), sizeof(uint32_t)));
    };

    uint32_t magic = 0;
    if (!read_u32(magic) || magic != 0x46455247) return std::nullopt;  // "GREF"

    uint32_t version = 0;
    if (!read_u32(version) || version != 1) return std::nullopt;

    GoldenReference ref;
    if (!read_u32(ref.width) || !read_u32(ref.height) || !read_u32(ref.base_channels))
        return std::nullopt;

    uint32_t denimodel_size = 0;
    if (!read_u32(denimodel_size)) return std::nullopt;
    ref.denimodel_bytes.resize(denimodel_size);
    if (!file.read(reinterpret_cast<char*>(ref.denimodel_bytes.data()), denimodel_size))
        return std::nullopt;

    uint32_t num_images = 0;
    if (!read_u32(num_images) || num_images != 7) return std::nullopt;

    for (uint32_t i = 0; i < num_images; ++i) {
        uint32_t name_len = 0;
        if (!read_u32(name_len)) return std::nullopt;
        std::string name(name_len, '\0');
        if (!file.read(name.data(), name_len)) return std::nullopt;

        uint32_t data_size = 0;
        if (!read_u32(data_size)) return std::nullopt;

        std::vector<uint16_t>* target = nullptr;
        if (name == "diffuse") target = &ref.diffuse;
        else if (name == "specular") target = &ref.specular;
        else if (name == "normals") target = &ref.normals;
        else if (name == "depth") target = &ref.depth;
        else if (name == "motion") target = &ref.motion;
        else if (name == "diffuse_albedo") target = &ref.diffuse_albedo;
        else if (name == "specular_albedo") target = &ref.specular_albedo;
        else return std::nullopt;

        target->resize(data_size / sizeof(uint16_t));
        if (!file.read(reinterpret_cast<char*>(target->data()), data_size))
            return std::nullopt;
    }

    uint32_t output_size = 0;
    if (!read_u32(output_size)) return std::nullopt;
    ref.expected_output.resize(output_size / sizeof(float));
    if (!file.read(reinterpret_cast<char*>(ref.expected_output.data()), output_size))
        return std::nullopt;

    return ref;
}

deni::vulkan::WeightData ParseDenimodel(const std::vector<uint8_t>& bytes) {
    size_t offset = 0;
    auto read_u32 = [&]() -> uint32_t {
        uint32_t val;
        std::memcpy(&val, bytes.data() + offset, sizeof(uint32_t));
        offset += sizeof(uint32_t);
        return val;
    };

    read_u32();  // magic: "DENI"
    read_u32();  // version: 1
    uint32_t num_layers = read_u32();
    read_u32();  // total_weight_bytes

    deni::vulkan::WeightData result;
    result.layers.reserve(num_layers);

    for (uint32_t i = 0; i < num_layers; ++i) {
        deni::vulkan::LayerWeights layer;

        uint32_t name_len = read_u32();
        layer.name.assign(reinterpret_cast<const char*>(bytes.data() + offset), name_len);
        offset += name_len;

        uint32_t num_dims = read_u32();
        layer.shape.resize(num_dims);
        uint32_t num_elements = 1;
        for (uint32_t d = 0; d < num_dims; ++d) {
            layer.shape[d] = read_u32();
            num_elements *= layer.shape[d];
        }

        layer.data.resize(num_elements);
        std::memcpy(layer.data.data(), bytes.data() + offset, num_elements * sizeof(float));
        offset += num_elements * sizeof(float);

        result.total_parameters += num_elements;
        result.layers.push_back(std::move(layer));
    }
    return result;
}

// ---------------------------------------------------------------------------
// Vulkan image helpers
// ---------------------------------------------------------------------------

struct TestImage {
    VkImage image = VK_NULL_HANDLE;
    VmaAllocation allocation = VK_NULL_HANDLE;
    VkImageView view = VK_NULL_HANDLE;
};

TestImage CreateTestImage(VkDevice device, VmaAllocator allocator,
                          VkFormat format, uint32_t w, uint32_t h) {
    VkImageCreateInfo img_ci{};
    img_ci.sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;
    img_ci.imageType = VK_IMAGE_TYPE_2D;
    img_ci.format = format;
    img_ci.extent = {w, h, 1};
    img_ci.mipLevels = 1;
    img_ci.arrayLayers = 1;
    img_ci.samples = VK_SAMPLE_COUNT_1_BIT;
    img_ci.tiling = VK_IMAGE_TILING_OPTIMAL;
    img_ci.usage = VK_IMAGE_USAGE_STORAGE_BIT | VK_IMAGE_USAGE_TRANSFER_DST_BIT |
                   VK_IMAGE_USAGE_TRANSFER_SRC_BIT;
    img_ci.initialLayout = VK_IMAGE_LAYOUT_UNDEFINED;

    VmaAllocationCreateInfo alloc_ci{};
    alloc_ci.usage = VMA_MEMORY_USAGE_GPU_ONLY;

    TestImage ti;
    VkResult result = vmaCreateImage(allocator, &img_ci, &alloc_ci,
                                     &ti.image, &ti.allocation, nullptr);
    REQUIRE(result == VK_SUCCESS);

    VkImageViewCreateInfo view_ci{};
    view_ci.sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO;
    view_ci.image = ti.image;
    view_ci.viewType = VK_IMAGE_VIEW_TYPE_2D;
    view_ci.format = format;
    view_ci.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};

    result = vkCreateImageView(device, &view_ci, nullptr, &ti.view);
    REQUIRE(result == VK_SUCCESS);
    return ti;
}

void DestroyTestImage(VkDevice device, VmaAllocator allocator, TestImage& ti) {
    if (ti.view != VK_NULL_HANDLE) vkDestroyImageView(device, ti.view, nullptr);
    if (ti.image != VK_NULL_HANDLE) vmaDestroyImage(allocator, ti.image, ti.allocation);
    ti = {};
}

struct StagingBuffer {
    VkBuffer buffer = VK_NULL_HANDLE;
    VmaAllocation allocation = VK_NULL_HANDLE;
    void* mapped = nullptr;
    VkDeviceSize size = 0;
};

StagingBuffer CreateStagingBuffer(VmaAllocator allocator, VkDeviceSize size) {
    VkBufferCreateInfo buf_ci{};
    buf_ci.sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;
    buf_ci.size = size;
    buf_ci.usage = VK_BUFFER_USAGE_TRANSFER_SRC_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT;

    VmaAllocationCreateInfo alloc_ci{};
    alloc_ci.usage = VMA_MEMORY_USAGE_CPU_ONLY;
    alloc_ci.flags = VMA_ALLOCATION_CREATE_MAPPED_BIT;

    VmaAllocationInfo alloc_info{};
    StagingBuffer sb;
    sb.size = size;
    VkResult result = vmaCreateBuffer(allocator, &buf_ci, &alloc_ci,
                                      &sb.buffer, &sb.allocation, &alloc_info);
    REQUIRE(result == VK_SUCCESS);
    sb.mapped = alloc_info.pMappedData;
    return sb;
}

void DestroyStagingBuffer(VmaAllocator allocator, StagingBuffer& sb) {
    if (sb.buffer != VK_NULL_HANDLE) vmaDestroyBuffer(allocator, sb.buffer, sb.allocation);
    sb = {};
}

void TransitionImage(VkCommandBuffer cmd, VkImage image,
                     VkImageLayout old_layout, VkImageLayout new_layout,
                     VkPipelineStageFlags2 src_stage, VkAccessFlags2 src_access,
                     VkPipelineStageFlags2 dst_stage, VkAccessFlags2 dst_access) {
    VkImageMemoryBarrier2 barrier{};
    barrier.sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER_2;
    barrier.oldLayout = old_layout;
    barrier.newLayout = new_layout;
    barrier.srcStageMask = src_stage;
    barrier.srcAccessMask = src_access;
    barrier.dstStageMask = dst_stage;
    barrier.dstAccessMask = dst_access;
    barrier.srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    barrier.dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED;
    barrier.image = image;
    barrier.subresourceRange = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1};

    VkDependencyInfo dep{};
    dep.sType = VK_STRUCTURE_TYPE_DEPENDENCY_INFO;
    dep.imageMemoryBarrierCount = 1;
    dep.pImageMemoryBarriers = &barrier;
    vkCmdPipelineBarrier2(cmd, &dep);
}

void UploadToImage(VkCommandBuffer cmd,
                   VkImage image,
                   uint32_t w, uint32_t h,
                   const void* data, VkDeviceSize data_size,
                   StagingBuffer& staging) {
    REQUIRE(data_size <= staging.size);
    std::memcpy(staging.mapped, data, data_size);

    TransitionImage(cmd, image,
                    VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
                    VK_PIPELINE_STAGE_2_TOP_OF_PIPE_BIT, 0,
                    VK_PIPELINE_STAGE_2_TRANSFER_BIT, VK_ACCESS_2_TRANSFER_WRITE_BIT);

    VkBufferImageCopy region{};
    region.imageSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
    region.imageExtent = {w, h, 1};
    vkCmdCopyBufferToImage(cmd, staging.buffer, image,
                           VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &region);

    TransitionImage(cmd, image,
                    VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, VK_IMAGE_LAYOUT_GENERAL,
                    VK_PIPELINE_STAGE_2_TRANSFER_BIT, VK_ACCESS_2_TRANSFER_WRITE_BIT,
                    VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
                    VK_ACCESS_2_SHADER_STORAGE_READ_BIT);
}

// ---------------------------------------------------------------------------
// Shared test fixture: loads golden reference, sets up Vulkan + GPU images
// ---------------------------------------------------------------------------

struct GoldenTestFixture {
    monti::app::VulkanContext& ctx = monti::test::SharedVulkanContext();
    GoldenReference ref;
    deni::vulkan::WeightData weight_data;
    std::unique_ptr<deni::vulkan::MlInference> ml;

    VkDevice device = VK_NULL_HANDLE;
    VmaAllocator allocator = VK_NULL_HANDLE;

    TestImage img_diffuse{};
    TestImage img_specular{};
    TestImage img_normals{};
    TestImage img_depth{};
    TestImage img_motion{};
    TestImage img_diffuse_albedo{};
    TestImage img_specular_albedo{};
    TestImage img_output{};
    StagingBuffer staging{};

    uint32_t w = 0;
    uint32_t h = 0;
    uint32_t hw = 0;

    bool Setup() {
        std::string golden_path = std::string(DENI_TEST_DATA_DIR) + "/golden_ref.bin";
        auto golden = LoadGoldenReference(golden_path);
        if (!golden.has_value()) {
            WARN("Golden reference file not found: " << golden_path
                 << " -- run generate_golden_reference.py to create it. Skipping.");
            return false;
        }

        ref = std::move(golden.value());
        w = ref.width;
        h = ref.height;
        hw = w * h;

        REQUIRE(ref.expected_output.size() == 3 * hw);

        weight_data = ParseDenimodel(ref.denimodel_bytes);
        REQUIRE(weight_data.layers.size() > 0);

        REQUIRE(ctx.Device() != VK_NULL_HANDLE);

        device = ctx.Device();
        allocator = ctx.Allocator();

        ml = std::make_unique<deni::vulkan::MlInference>(device,
                                            allocator, vkGetDeviceProcAddr,
                                            DENI_SHADER_SPV_DIR, VK_NULL_HANDLE, w, h);
        {
            VkCommandBuffer cmd = ctx.BeginOneShot();
            REQUIRE(ml->LoadWeights(weight_data, cmd));
            ctx.SubmitAndWait(cmd);
            ml->FreeStagingBuffer();
        }
        REQUIRE(ml->IsReady());

        img_diffuse  = CreateTestImage(device, allocator, VK_FORMAT_R16G16B16A16_SFLOAT, w, h);
        img_specular = CreateTestImage(device, allocator, VK_FORMAT_R16G16B16A16_SFLOAT, w, h);
        img_normals  = CreateTestImage(device, allocator, VK_FORMAT_R16G16B16A16_SFLOAT, w, h);
        img_depth    = CreateTestImage(device, allocator, VK_FORMAT_R16_SFLOAT, w, h);
        img_motion   = CreateTestImage(device, allocator, VK_FORMAT_R16G16_SFLOAT, w, h);
        img_diffuse_albedo  = CreateTestImage(device, allocator,
                                              VK_FORMAT_R16G16B16A16_SFLOAT, w, h);
        img_specular_albedo = CreateTestImage(device, allocator,
                                              VK_FORMAT_R16G16B16A16_SFLOAT, w, h);
        img_output   = CreateTestImage(device, allocator, VK_FORMAT_R16G16B16A16_SFLOAT, w, h);

        VkDeviceSize max_staging = w * h * 8;
        staging = CreateStagingBuffer(allocator, max_staging);

        auto upload_one = [&](VkImage image, const void* data, VkDeviceSize bytes) {
            VkCommandBuffer cmd = ctx.BeginOneShot();
            UploadToImage(cmd, image, w, h, data, bytes, staging);
            ctx.SubmitAndWait(cmd);
        };
        upload_one(img_diffuse.image,  ref.diffuse.data(),  ref.diffuse.size()  * 2);
        upload_one(img_specular.image, ref.specular.data(), ref.specular.size() * 2);
        upload_one(img_normals.image,  ref.normals.data(),  ref.normals.size()  * 2);
        upload_one(img_depth.image,    ref.depth.data(),    ref.depth.size()    * 2);
        upload_one(img_motion.image,   ref.motion.data(),   ref.motion.size()   * 2);
        upload_one(img_diffuse_albedo.image,  ref.diffuse_albedo.data(),
                   ref.diffuse_albedo.size()  * 2);
        upload_one(img_specular_albedo.image, ref.specular_albedo.data(),
                   ref.specular_albedo.size() * 2);
        {
            VkCommandBuffer cmd = ctx.BeginOneShot();
            TransitionImage(cmd, img_output.image,
                            VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_GENERAL,
                            VK_PIPELINE_STAGE_2_TOP_OF_PIPE_BIT, 0,
                            VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
                            VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT);
            ctx.SubmitAndWait(cmd);
        }
        return true;
    }

    deni::vulkan::DenoiserInput MakeInput() const {
        deni::vulkan::DenoiserInput input{};
        input.noisy_diffuse   = img_diffuse.view;
        input.noisy_specular  = img_specular.view;
        input.world_normals   = img_normals.view;
        input.linear_depth    = img_depth.view;
        input.motion_vectors  = img_motion.view;
        input.diffuse_albedo  = img_diffuse_albedo.view;
        input.specular_albedo = img_specular_albedo.view;
        input.render_width    = w;
        input.render_height   = h;
        return input;
    }

    std::vector<float> RunInference() {
        auto input = MakeInput();

        VkCommandBuffer cmd = ctx.BeginOneShot();
        TransitionImage(cmd, img_output.image,
                        VK_IMAGE_LAYOUT_UNDEFINED, VK_IMAGE_LAYOUT_GENERAL,
                        VK_PIPELINE_STAGE_2_TOP_OF_PIPE_BIT, 0,
                        VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
                        VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT);
        ml->Infer(cmd, input, img_output.view);
        TransitionImage(cmd, img_output.image,
                        VK_IMAGE_LAYOUT_GENERAL,
                        VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
                        VK_PIPELINE_STAGE_2_COMPUTE_SHADER_BIT,
                        VK_ACCESS_2_SHADER_STORAGE_WRITE_BIT,
                        VK_PIPELINE_STAGE_2_TRANSFER_BIT,
                        VK_ACCESS_2_TRANSFER_READ_BIT);

        VkBufferImageCopy region{};
        region.imageSubresource = {VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1};
        region.imageExtent = {w, h, 1};
        vkCmdCopyImageToBuffer(cmd, img_output.image,
                               VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
                               staging.buffer, 1, &region);
        ctx.SubmitAndWait(cmd);

        auto* fp16 = static_cast<const uint16_t*>(staging.mapped);
        std::vector<float> result(3 * hw);
        for (uint32_t y = 0; y < h; ++y) {
            for (uint32_t x = 0; x < w; ++x) {
                uint32_t px = y * w + x;
                result[0 * hw + px] = HalfToFloat(fp16[px * 4 + 0]);
                result[1 * hw + px] = HalfToFloat(fp16[px * 4 + 1]);
                result[2 * hw + px] = HalfToFloat(fp16[px * 4 + 2]);
            }
        }
        return result;
    }

    void Teardown() {
        ctx.WaitIdle();
        DestroyStagingBuffer(allocator, staging);
        DestroyTestImage(device, allocator, img_output);
        DestroyTestImage(device, allocator, img_specular_albedo);
        DestroyTestImage(device, allocator, img_diffuse_albedo);
        DestroyTestImage(device, allocator, img_motion);
        DestroyTestImage(device, allocator, img_depth);
        DestroyTestImage(device, allocator, img_normals);
        DestroyTestImage(device, allocator, img_specular);
        DestroyTestImage(device, allocator, img_diffuse);
    }
};

}  // namespace

// ===========================================================================
// Test cases
// ===========================================================================

// Golden reference test: compare GPU shader output against PyTorch inference.
//
// The expected output in golden_ref.bin is produced by running the actual
// training model (training/deni_train/models/unet.py DeniUNet) with random
// weights on deterministic input. If the model architecture changes, regenerate
// the golden reference and update the GPU shaders to match.
TEST_CASE("MlInference: GPU output matches PyTorch golden reference",
          "[deni][numerical][golden]") {
    GoldenTestFixture fix;
    if (!fix.Setup()) return;

    auto gpu_output = fix.RunInference();

    float max_abs_error = 0.0f;
    float sum_sq_error = 0.0f;
    uint32_t num_elements = 3 * fix.hw;

    for (uint32_t i = 0; i < num_elements; ++i) {
        float err = std::abs(gpu_output[i] - fix.ref.expected_output[i]);
        max_abs_error = std::max(max_abs_error, err);
        sum_sq_error += err * err;
    }
    float rmse = std::sqrt(sum_sq_error / static_cast<float>(num_elements));

    std::fprintf(stderr,
                 "\n=== Golden Reference Validation (GPU vs PyTorch) ===\n"
                 "  Resolution:       %u x %u\n"
                 "  base_channels:    %u\n"
                 "  Output elements:  %u (3 channels x %u pixels)\n"
                 "  Max abs error:    %.6f\n"
                 "  RMSE:             %.6f\n"
                 "=====================================================\n",
                 fix.w, fix.h, fix.ref.base_channels, num_elements, fix.hw,
                 max_abs_error, rmse);

    std::fprintf(stderr, "  First 5 pixels (GPU vs PyTorch):\n");
    for (uint32_t px = 0; px < std::min(5u, fix.hw); ++px) {
        std::fprintf(stderr,
                     "    px[%u]: GPU=(%.4f, %.4f, %.4f)  PyTorch=(%.4f, %.4f, %.4f)\n",
                     px,
                     gpu_output[0 * fix.hw + px], gpu_output[1 * fix.hw + px],
                     gpu_output[2 * fix.hw + px],
                     fix.ref.expected_output[0 * fix.hw + px],
                     fix.ref.expected_output[1 * fix.hw + px],
                     fix.ref.expected_output[2 * fix.hw + px]);
    }

    // Tolerance: The GPU path stores intermediate feature maps in FP16 between
    // compute dispatches, while PyTorch keeps all intermediates in FP32. The
    // albedo remodulation step multiplies through FP16-quantized albedo.
    // Measured error with base_channels=8, 32x32, seed 42: RMSE ~0.003, max_abs ~0.012.
    CHECK(rmse < 0.004f);
    CHECK(max_abs_error < 0.015f);

    uint32_t outliers = 0;
    for (uint32_t i = 0; i < num_elements; ++i) {
        if (std::abs(gpu_output[i] - fix.ref.expected_output[i]) > 0.015f) ++outliers;
    }
    CHECK(outliers == 0);

    fix.Teardown();
}

// Verify GPU inference is bit-exact deterministic across multiple runs.
TEST_CASE("MlInference: output is deterministic across multiple runs",
          "[deni][numerical][determinism]") {
    GoldenTestFixture fix;
    if (!fix.Setup()) return;

    auto run1 = fix.RunInference();
    auto run2 = fix.RunInference();

    REQUIRE(run1.size() == run2.size());
    for (uint32_t i = 0; i < run1.size(); ++i)
        CHECK(run1[i] == run2[i]);

    fix.Teardown();
}
